EditorExtensions/Shared/Compilers/ServerBase.cs
As discussed in the Fiddler book (http://fiddlerbook.com/fiddler/help/hookup.asp#Q-LocalTraffic), `System.Net.Http.HttpClient` is hard-coded to avoid proxies when `localhost` or `127.0.0.1` is provided as the address.  
Using `localhost.` seems to be the most universal fix for this, as it will resolve whether or not Fiddler (or any other local proxy) is actually running.
=> Bypass hard-coded no-proxy restrictions on localhost to allow Fiddler debugging

EditorExtensions/Resources/Scripts/JSDocComments.js
I see that another change was made to attempt to fix this, but the RegExp was still incorrect. This version splits JsDocs lines correctly. No unit test, but I've been making this exact change locally in on my daily development system for months.
=> Fixed RegExp for splitting JsDoc lines

EditorExtensions/Source.extension.vsixmanifest
Web Essentials 2013 cannot currently be installed on systems where Visual Studio 2015 CTP has been installed side by side with VS 2013, since Visual Studio 2015 performs an in place upgrade of .NET 4.5 to .NET 4.5.3. The extension.vsixmanifest, however, explicitly targets 4.5. Changing to [4.5,) resolves #1737.
=> Modified dependency on .NET 4.5 to .NET [4.5,)

EditorExtensions/CSS/QuickInfo/Image/ImageQuickInfo.cs
I've found a bug when image size is calculated improperly for some of the PhotoShop-generated PNG images. I'm attaching one such image to the issue.
I've found that the problem with image calculation is the problem with incorrectly (IMHO) used [`BitmapSource.Width` property](https://msdn.microsoft.com/en-us/library/system.windows.media.imaging.bitmapsource.width(v=vs.110).aspx). I've used the `PixelWidth` and `PixelHeight` instead and I got the proper results for the test image.
Here is the image (it has physical size `46x49` but is incorrectly shown as `61x65` by the actual Web Essentials):
To test the issue I've created the followed CSS file:
```css
.my-class {
background: url('pixels.png');
}
```
When I'm hovering mouse cursor over `pixels.png` I can see incorrect size in the tooltip …
=> Change image size calculation

EditorExtensions/Markdown/Margin/MarkdownMargin.cs, EditorExtensions/Shared/Compilers/CompilerNotifierProviders.cs, EditorExtensions/Shared/Compilers/CompilerRunner.cs, EditorExtensions/Shared/Helpers/FileHelpers.cs
Fix Issue #1762 
This fix also a bug that was causing a NullReferenceException when a markdown file that was not part of a project or solution was opened and the code attempted to get the Active Project path.
=> Better support of Unicode/ANSI markdown files without BOM

EditorExtensions/PreBuildTask.cs, EditorExtensions/Resources/server/services/srv-less.js, EditorExtensions/Resources/server/services/srv-rubyscss.js, EditorExtensions/Resources/server/services/srv-scss.js, EditorExtensions/WebEssentials2013.csproj, EditorExtensions/packages.config
* Downloads lastest npm matching with node.js
latest stable release. (solution inspired by
[nvmw](https://github.com/hakobera/nvmw)).
* Updates Sass service to comply with v3 changes.
* Updates Nuget packages.
@madskristensen, someone commented out the explicit inclusions in `csproj` file. We will need to test it once we get it to build. It still throws error with final routine, when copying files to packages. The `PreBuildTask` is executing successfully though. @SLaks, some packages (like `IcedCoffeeScript`) are not flattened. They still have `node_modules` subdirectory. Any ideas what is going wrong?
=> Package: Updates MSBuild task to fix PathTooLong

EditorExtensions/Settings/WESettings.cs
Fixed a typo: Changed the DisplayName from 'Optmize' to 'Optimize'
=> Fixed a typo in Sprite Settings

EditorExtensions/WebEssentials2013.csproj, EditorExtensions/packages.config
Fixed a bug #1818 «Minify Angular.js binding expressions causes exception with ngRepeat».
=> HTML: Update WebMarkupMin to version 0.9.12

EditorExtensions/Markdown/Margin/MarkdownMargin.cs, EditorExtensions/Settings/WESettings.cs
Created a settings option to specify the location of a global CSS file that will be applied to the markdown preview. If a solution level or project level file is found, that file will override this global file.
This is very similar to pull request [#1469](https://github.com/madskristensen/WebEssentials2013/pull/1469) but should be an easier merge as it was just forked this morning.
One thing to note, I hope the language I used in the settings dialog (for both the setting name and setting description) is sufficient. I'm not the greatest wordsmith out there.
=> Markdown: Add global CSS setting.

EditorExtensions/HTML/Completion/TwitterCardCompletion.cs
This PR fixes a little bug in code intellisense - by default (and before this fix) WE2013 inserts invalid key value for Twitter's summary card preventing validation:
https://dev.twitter.com/cards/types/summary-large-image
The correct markup for this Twitter card type should be:
```html
<meta name="twitter:card" content="summary_large_image">
```
This commit fixes a typo in Twitter Card summary with large image
type key value. Having incorrect value here would prevent Twitter Card
from being validated on submission to Twitter for white-listing
Thanks!
=> Correct Twitter card type. Fixes #1807

BuildTasks/BuildTasks.csproj, BuildTasks/NodeInstaller.cs, BuildTasks/Properties/AssemblyInfo.cs, BuildTasks/packages.config, EditorExtensions/WebEssentials2013.csproj, WebEssentials2013.sln
- Make solution open in VS2015 (still builds & deploys to 2013)
- Separate pre-build task into its own project for better development & debugging
- Permanently fix all path-too-long errors with a much more aggressive flattener
- More aggressively remove duplicate module versions for a smaller VSIX
If you get build errors from `BuildTasks` that the file is in use, kill all MSBuild processes and try again.
We should probably make the prebuild task skip everything if the files are already up to date (perhaps update only once a week?)
=> Fix Pre-build task (fixes #1452)

EditorExtensions/BrowserLink/BestPractices/BestPracticesBrowserLink.cs, EditorExtensions/BrowserLink/BestPractices/Rules/RulesFactory.cs, EditorExtensions/Settings/WESettings.cs
Add an option to disable the validation about microdata. 
Turning this switch to false will remove this error message that can be useless for an intranet application per example.
SEO: Use HTML5 microdata to add semantic meaning to the website.
This could fix #1878 
I will copy this modification to WE2015 if this PR is accepted.
=> Validation: Add a switch to disable SEO microdata validation

BuildTasks/NodeInstaller.cs
With this, I am able to build the solution from scratch (after deleting all `\bin`, `\obj`, `packages`, `EditorExtensions\Resoruces\nodejs` or simply a fresh clone).
=> Build: Prevents from throwing on delete

EditorExtensions/Shared/Linters/LintReporter.cs
This will make Error List match the navigated cursor position.
Fixes #1845.
=> Lint: Makes line/column consistent in Error List

EditorExtensions/Resources/server/services/srv-autoprefixer.js, EditorExtensions/Resources/server/services/srv-less.js, EditorExtensions/Resources/server/services/srv-scss.js, EditorExtensions/Shared/Helpers/CssSourceMap.cs, EditorExtensions/WebEssentials2013.csproj
* Removes fallback VLQ cure for sass since sass/libsass#324 is fixed.
* `.ToList()` to eagerly load VLQ maps. The subsequent `.Count()` was
causing redundant processing of all mappings (which is pretty
expensive).
* Autoprefix takes stringly maps and returns object for map. So we are
strigifying returned map in Less and Sass.
=> SourceMap: Fixes for CSS source-map processing

EditorExtensions/Resources/server/services/srv-less.js, EditorExtensions/SCSS/Compilers/ScssCompiler.cs, EditorExtensions/Settings/WESettings.cs, EditorExtensions/Shared/Compilers/CssCompilerBase.cs
Fixes #1465, #1837 and some others.
=> CSS: Makes relative-paths disableable via setting

EditorExtensions/LESS/Compilers/LessCompiler.cs, EditorExtensions/Resources/server/services/srv-less.js, EditorExtensions/SCSS/Compilers/ScssCompiler.cs, EditorExtensions/Shared/Compilers/CssCompilerBase.cs
* Passes user setting to Less compiler.
* Sass compiler does not provide the setting, so I have moved
`PostProcessResult()` to `SassCompiler` derived class.
Next we need to stitch the decoded source-maps into normalizer to get
the correct paths in import scenarios.
=> Code: Path fixes for [Le/Sa]ss compilers

BuildTasks/NodeInstaller.cs
@madskristensen, this delta fixes the jshint dependency `shelljs` issue we discussed, where shelljs has a source file `shelljs/src/test.js` which is `require()`d.
=> Build: Removes exclusion that breaks jshint

EditorExtensions/Misc/Bundles/BundleFilesObserver.cs
In #1918, the reported exception is a false-positive as the observer
was firing the change event twice. This fixes the root-cause of the
problem (instead of catching the exception in `CssUrlNormalizer.FixPath(_)`).
---
Also took some ReSharper suggestions.  
If required, I can squash those commits.
@SLaks, PTAL.
=>  Bundle: Detach the event on change

EditorExtensions/Shared/Helpers/Css/CssUrlNormalizer.cs
The variable names were conflicting. 
This change follows the convention of having class private member names starting with `_` (unless it is a collection, which should start with capital letter).
Closes #1918.
=> CssNormalizer: Fixes bug #1918

EditorExtensions/Resources/server/services/srv-less.js
This is for Less compiler can resolve the relative path.
I somehow forgot the incorporate this bit.. :disappointed:
Related discussion: less/less.js#2084
Fixes #1922.
=> srv-less: Adds the missing rootpath option

EditorExtensions/Resources/server/services/srv-autoprefixer.js, EditorExtensions/Resources/server/services/srv-less.js
This fixes two things:
* Deprecated warning for autoprefixer:
>  Autoprefixer's process() method is deprecated and will removed in next major release. 
Use postcss([autoprefixer]).process() instead
* Stringify Map file when processed from autoprefixer; so when `autoprefixer` and `rtlcss` are `True`, it should not re-stringify the map output.
=> node-services: Fixes a map content type bug

EditorExtensions/Misc/Bundles/BundleGenerator.cs, EditorExtensions/Settings/WESettings.cs
I have added a parameter baseUrl to solution settings that is used when generating JavaScript map files, so the map file will point to the original JS files using this base url.
=> Use a baseUrl setting to reference original JS files inside a map file.

EditorExtensions/Misc/Minification/IFileMinifier.cs, EditorExtensions/Settings/WESettings.cs, EditorExtensions/WebEssentials2013.csproj, EditorExtensions/packages.config
This property allows to preserve case of tag and attribute names during HTML minification (useful for Angular 2 templates).
=> Add `PreserveCase` property to HTML minification settings
